graphhopper:
  datareader.file: /home/denbura/working/denbura/data/osm/kanto-latest.osm.pbf
  graph.location: /home/denbura/working/denbura/data/graph-cache

  graph.encoded_values: car_access, car_average_speed, road_access

  profiles:
    - name: car
      custom_model_files: [car.json]

  profiles_ch:
    - profile: car

  import.osm.ignored_highways: footway,construction,cycleway,path,steps

server:
  application_connectors:
    - type: http
      port: 2027
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 2028
      bind_host: localhost
